// Generates db/cards.sql (idempotent INSERT OR REPLACE) from data/cards.json for the D1 `cards` table.
// Image links point at our CDN (same naming as cardImageUrl in app/utils/assets.ts), not the source dataset's.
//
//   npm run db:seed:cards        (generate + load into remote D1)
//   npm run cards:sql            (generate only)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const CDN = 'https://cdn.seethespire.com'
const SOURCE = 'data/cards.json'
const OUT = 'db/cards.sql'

type Json = null | boolean | number | string | Json[] | { [key: string]: Json }
type SourceCard = Record<string, Json>

const COLUMNS = [
  'id', 'name', 'description', 'description_raw', 'upgrade_description', 'upgrade', 'cost', 'is_x_cost',
  'star_cost', 'is_x_star_cost', 'type', 'type_key', 'rarity', 'rarity_key', 'target', 'color', 'damage',
  'block', 'hit_count', 'cards_draw', 'energy_gain', 'hp_loss', 'keywords', 'tags', 'powers_applied',
  'spawns_cards', 'vars', 'type_variants', 'sources', 'can_be_generated_in_combat', 'multiplayer_only',
  'compendium_order', 'image_url', 'image_url_upgraded'
] as const

const JSON_COLUMNS = new Set(['upgrade', 'keywords', 'tags', 'powers_applied', 'spawns_cards', 'vars', 'type_variants', 'sources'])

function sqlValue(value: Json | undefined, column: string): string {
  if (value === null || value === undefined) return 'NULL'
  if (JSON_COLUMNS.has(column)) return sqlString(JSON.stringify(value))
  if (typeof value === 'boolean') return value ? '1' : '0'
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL'
  if (typeof value === 'string') return sqlString(value)
  return sqlString(JSON.stringify(value))
}

function sqlString(text: string): string {
  return `'${text.replace(/'/g, "''")}'`
}

const cards = JSON.parse(readFileSync(SOURCE, 'utf8')) as SourceCard[]
const seen = new Set<string>()

const rows = cards.map(card => {
  const id = String(card.id ?? '').replace(/^CARD\./, '')
  if (!id || !card.name) throw new Error(`Card without id/name: ${JSON.stringify(card).slice(0, 120)}`)
  if (seen.has(id)) throw new Error(`Duplicate card id ${id}`)
  seen.add(id)

  const slug = id.toLowerCase()
  const row: Record<string, Json | undefined> = {
    ...card,
    id,
    image_url: `${CDN}/cards/${slug}.png`,
    // `upgrade` is null for cards that can't be upgraded (curses, statuses, ...).
    image_url_upgraded: card.upgrade ? `${CDN}/cards/${slug}_plus.png` : null
  }
  const values = COLUMNS.map(column => sqlValue(row[column], column)).join(', ')
  return `INSERT OR REPLACE INTO cards (${COLUMNS.join(', ')}) VALUES (${values});`
})

mkdirSync('db', { recursive: true })
writeFileSync(OUT, `-- Generated by scripts/build-cards-sql.ts from ${SOURCE}. Do not edit by hand.\n${rows.join('\n')}\n`)
console.log(`Wrote ${rows.length} cards to ${OUT}`)
